FROM golang:1.10.1
LABEL MAINTAINER="MingH <houming@smm.cn>"

RUN apk add --update git

COPY . /go/src/github.com/arachnys/athenapdf/weaver
WORKDIR /go/src/github.com/arachnys/athenapdf/weaver

RUN \
  go get -v -d \
  && go install -v \
  && CGO_ENABLED=0 go build -ldflags "-s" -a -installsuffix cgo -o pdfcenter .

CMD ["/bin/sh"]
